### ISSUE TITLE
-doAsso 5 with Beagle 3.3 output

### ISSUE THREAD

**Issue by clydeandforth** [ANGSD/angsd#313]
Hi,

I would like to do an association test and estimate the effect size with the -doAsso 5 option. I have estimated the genotype likelihoods using this command:

```

module load moab torque openmpi/gcc/64/1.10.2 gromacs/5.1.2-plumed tools htslib/1.9 angsd/0.931

angsd -nThreads OMP_NUM_THREADS -bam bam_list.txt -anc BATG-0.5-CLCbioSSPACE.fa -ref BATG-0.5-CLCbioSSPACE.fa  -out angsd_out -doGlf 2 -doMaf 1 -SNP_pval 1e-6 -doGeno 5 -baq 1 -minQ 20 -doPost 2 -postCutoff 0.5 -geno_minDepth 2 -only_proper_pairs 1
```

This was the tail of the log file:
```
->"angsd_out.arg"
		->"angsd_out.beagle.gz"
		->"angsd_out.mafs.gz"
		->"angsd_out.geno.gz"
	-> Tue May  5 03:48:38 2020
	-> Arguments and parameters for all analysis are located in .arg file
	-> Total number of sites analyzed: 717420505
	-> Number of sites retained after filtering: 40739738 
	[ALL done] cpu-time used =  444821.00 sec
	[ALL done] walltime used =  410308.00 sec

```
All looks fine so I then tried imputation via Beagle 3.3 with this command: 

```
module load tools oracle_jdk/1.6.0_45
java -Xmx100g -jar beagle.jar like=angsd_out.beagle.gz  out=beagleOut
```

However I get the following error:

```
Exception in thread "main" java.lang.NegativeArraySizeException
        at phaser.G.<init>(Unknown Source)
        at phaser.az.<init>(Unknown Source)
        at phaser.H.a(Unknown Source)
        at phaser.ae.a(Unknown Source)
        at phaser.PhaseMain.<init>(Unknown Source)
        at phaser.PhaseMain.main(Unknown Source)

```

I'm not sure what's going wrong here? The beagle.gz file looks good:

```
zcat angsd_out_fat.beagle.gz | head
marker	allele1	allele2	Ind0	Ind0	Ind0	Ind1	Ind1	Ind1	Ind2	Ind2	Ind2	Ind3	Ind3	Ind3	Ind4	Ind4	Ind4	Ind5	Ind5	Ind5	Ind6	Ind6	Ind6	Ind7	IndInd7	Ind8	Ind8	Ind8	Ind9	Ind9	Ind9	Ind10	Ind10	Ind10	Ind11	Ind11	Ind11	Ind12	Ind12	Ind12	Ind13	Ind13	Ind13	Ind14	Ind14	Ind14	Ind15	Ind15	Ind15	Ind16	Ind16	Ind16	Ind17	Ind17	Ind17	Ind18	Ind18	Ind18	Ind19	Ind19	Ind19	Ind20	Ind20	Ind20	Ind21	Ind21	Ind21	Ind22	Ind22	Ind22	Ind23	Ind23	Ind23	Ind24	Ind24	Ind24	Ind25	Ind25	Ind25	Ind26	Ind26	Ind26	Ind27	Ind27	Ind27	Ind28	Ind28	Ind28	Ind29	Ind29	Ind29	Ind30	Ind30	Ind30	Ind31	Ind31	Ind31	Ind32	Ind32	Ind32	Ind33	Ind33	Ind33	Ind34	Ind34	Ind34	Ind35	Ind35	Ind35	Ind36	Ind36	Ind36	Ind37	Ind37	Ind37	Ind38	Ind38	Ind38	Ind39	Ind39	Ind39	Ind40	Ind40	Ind40	Ind41	Ind41	Ind41	Ind42	Ind42	Ind42	Ind43	Ind43	Ind43	Ind44	Ind44	Ind44	Ind45	Ind45	Ind45	Ind46	Ind46	Ind46	Ind47	Ind47	Ind47	Ind48	Ind48	Ind48	Ind49	Ind49	Ind49	Ind50	Ind50	Ind50	Ind51	Ind51	Ind51	Ind52	Ind52	Ind52	Ind53	Ind53	Ind53	Ind54	Ind54	Ind54	Ind55	Ind55	Ind55	Ind56	Ind56	Ind56	Ind57	Ind57	Ind57	Ind58	Ind58	Ind58	Ind59	Ind59	Ind59	Ind60	Ind60	Ind60	Ind61	Ind61	Ind61	Ind62	Ind62	Ind62	Ind63	Ind63	Ind63	Ind64	Ind64	Ind64	Ind65	Ind65	Ind65	Ind66	Ind66	Ind66	Ind67	Ind67	Ind67	Ind68	Ind68	Ind68	Ind69	Ind69	Ind69	Ind70	Ind70	Ind70	Ind71	Ind71	Ind71	Ind72	Ind72	Ind72	Ind73	Ind73	Ind73	Ind74	Ind74	Ind74	Ind75	Ind75	Ind75	Ind76	Ind76	Ind76	Ind77	Ind77	Ind77	Ind78	Ind78	Ind78	Ind79	Ind79	Ind79	Ind80	Ind80	Ind80	Ind81	Ind81	Ind81	Ind82	Ind82	Ind82	Ind83	Ind83	Ind83	Ind84	Ind84	Ind84	Ind85	Ind85	Ind85	Ind86	Ind86	Ind86	Ind87	Ind87	Ind87	Ind88	Ind88	Ind88	Ind89	Ind89	Ind89	Ind90	Ind90	Ind90	Ind91	Ind91	Ind91	Ind92	Ind92	Ind92	Ind93	Ind93	Ind93	Ind94	Ind94	Ind94	Ind95	Ind95	Ind95	Ind96	Ind96	Ind96	Ind97	Ind97	Ind97	Ind98	Ind98	Ind98	Ind99	Ind99	Ind99	Ind100	Ind100	Ind100
Contig0_50	0	2	0.984616	0.015384	0.000000	0.941178	0.058822	0.000000	0.000001	0.999999	0.000000	0.984616	0.015384	0.000000	0.888891	0.111109	0.000000	0.981401	0.018599	0.000000	0.969698	0.030302	0.000000	0.888891	0.111109	0.000000	0.99
```

Is it possible to do an association with a VCF file from a newer version of Beagle?

Thanks,

James

**Comment by ANGSD** [comment]
Hello James there is some pretty rudimentary vcf/bcf reading implemented. Could you send me a subset of your vcf/bcf and ill look into adding support for that (I assume it is the gp tag that is lagging).

**Comment by clydeandforth** [comment]
Hi,

I hadn't created a vcf file for the genotype likelihood estimates as I had hoped to do the imputation in Beagle 3.3 and then do the association in Angsd. 

Thanks

James

**Comment by e-jorsboe** [comment]
Hi James, 

Have you checked that it is not simply due to the fact that your alleles are coded with numbers instead of letters? (In the beagle 3.3 manual they only show the .beagle file with letters?)

And also in the snippet of the .beagle you show (5th box), there are not genotype probabilities for all individuals? But that might be due to how many characters you can paste on github?

**Comment by clydeandforth** [comment]
Hi,
I think the error must have been memory related.
Beagle completed when I used a smaller sample set.

To get my larger sample set through Beagle I had to split the Angsd output file into 20 smaller files and process them individually, then concatenated the gprobs.gz output files. Like this (Java 1.8):

`zcat angsd_out_fat.beagle.gz | tail -n +2 | split -d -l 2036987 - split_
for file in split_*
do
    zcat angsd_out.beagle.gz | head -n 1  > tmp_file
    cat "$file" >> tmp_file
    mv -f tmp_file "$file"
done

for i in {00..19}; do
java -Xmx15000m -jar beagle.jar like=split_"$i"   out=split_"$i"_out
done

zcat split_00_out.split_00.gprobs.gz | head -n 1  > combine_gprobs.txt && for i in {00..19}; do zcat split_"$i"_out.split_"$i".gprobs.gz | tail -n +2  >> combine_gprobs.txt ; done`

**Comment by e-jorsboe** [comment]
Btw, please notice that ANGSD can now run "-doAsso" with genotype probabilities from bcf/vcf files using the genotype field "GP" as explained in the documentation for VCF files. Using this command:

./angsd -doMaf 4 -vcf-gp test/assotest/test.vcf -yBin test/assotest/test.phe -doAsso 4  -out test

VCF files can both be run with a .sample file containing phenotypes and covariates, or a separate phenotype file and covariate file (use -cov).

**Comment by clydeandforth** [comment]
Thanks. Is it possible to get the effect size from a vcf file, i.e. -doAsso 5 ?

**Comment by e-jorsboe** [comment]
Hi,

Yes it is possible to do -doAsso 4 (EM algorithm modelling the genotype as a latent variable), -doAsso 5 (dosage model), -doAsso 6 (hybrid model first running score model, and then for significant variants running the EM algorithm). 

-doAsso 4 and 5 give estimates of the effect size for all variant. -doAsso 6 gives estimates of the effect size for variants that are significant, meaning have a P-value/LRT value under/above a certain threshold. 

Does this make sense?

**Comment by clydeandforth** [comment]
Yes thanks. I previously used -doAsso 5, but I want to get reported estimates of the effect sizes for SNPs that are significant based on quantitative traits so I will change this to -doAsso 6. 
James

**Comment by clydeandforth** [comment]
Hi,

I reopened this issue as I used the `-vcf-gp` command but got the following error message:

```
BAD SITE Contig1:444234. return code:-3 while fetching GP tag rec->rid:1
BAD SITE Contig1:444242. return code:-3 while fetching GP tag rec->rid:1
BAD SITE Contig1:444254. return code:-3 while fetching GP tag rec->rid:1
BAD SITE Contig1:444255. return code:-3 while fetching GP tag rec->rid:1
BAD SITE Contig1:444267. return code:-3 while fetching GP tag rec->rid:1
BAD SITE Contig1:444298. return code:-3 while fetching GP tag rec->rid:1
BAD SITE Contig1:444307. return code:-3 while fetching GP tag rec->rid:1
BAD SITE Contig1:444318. return code:-3 while fetching GP tag rec->rid:1
BAD SITE Contig1:444320. return code:-3 while fetching GP tag rec->rid:1
BAD SITE Contig1:444325. return code:-3 while fetching GP tag rec->rid:1
BAD SITE Contig1:444328. return code:-3 while fetching GP tag rec->rid:1
BAD SITE Contig1:444329. return code:-3 while fetching GP tag rec->rid:1
BAD SITE Contig1:444346. return code:-3 while fetching GP tag rec->rid:1
BAD SITE Contig1:444362. return code:-3 while fetching GP tag rec->rid:1
BAD SITE Contig1:444364. return code:-3 while fetching GP tag rec->rid:1

```

Full command:

`angsd -doAsso 6 -yQuant leaf_loss.txt -cov test_pca.cov -doMaf 4 -vcf-gp beagle_vcf_test.vcf.gz -out assoc_vcf_out
`

`angsd version: 0.933-71-g604e1a4 (htslib: 1.10.2-41-g3b1ff68) build(Jun 16 2020 10:19:54)
`

Here is my input vcf file from Beagle 5.1:
 
```
##fileformat=VCFv4.2
##filedate=20200615
##source="beagle.18May20.d20.jar"
##INFO=<ID=AF,Number=A,Type=Float,Description="Estimated ALT Allele Frequencies">
##INFO=<ID=DR2,Number=1,Type=Float,Description="Dosage R-Squared: estimated squared correlation between estimated REF dose [P(RA) + 2*P(RR)] and true REF dose">
##INFO=<ID=IMP,Number=0,Type=Flag,Description="Imputed marker">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=DS,Number=A,Type=Float,Description="estimated ALT dose [P(RA) + 2*P(AA)]">
##FORMAT=<ID=GP,Number=G,Type=Float,Description="Estimated Genotype Probability">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	
```

list of bam files cut out here

```
Contig0	14	.	C	T	.	PASS	.	GT	0|0	0|0	0|1	0|1	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|1	0|0	0|0	0|1	0|0	0|00|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|1	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|00|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|1	0|0	0|0	0|00|0	0|0	0|0	0|0	0|0	0|1	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|1	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|00|0	0|0	0|0	0|0	0|0	0|0
Contig0	46	.	G	T	.	PASS	.	GT	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|1	0|0	0|00|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|00|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|00|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|00|0	0|0	0|0	0|0	0|0	0|0
Contig0	50	.	A	G	.	PASS	.	GT	0|0	0|0	0|1	0|1	0|0	0|0	0|0	0|1	0|0	0|0	0|0	0|1	0|0	0|0	1|0	0|0	0|00|0	0|0	0|0	0|0	0|1	0|0	0|0	0|0	0|0	0|1	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|1	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|00|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|1	0|0	0|0	0|0	0|1	0|0	1|0	0|0	0|0	0|10|0	0|0	0|0	0|0	0|0	0|1	0|0	0|1	0|0	0|0	0|0	0|1	0|0	0|1	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|1	0|00|0	0|0	0|0	0|0	0|0	0|0
Contig0	66	.	G	A	.	PASS	.	GT	0|0	0|0	0|0	0|0	0|1	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|00|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|00|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|00|0	0|1	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|00|0	0|0	0|0	0|0	0|0	0|0
Contig0	95	.	T	C	.	PASS	.	GT	0|0	0|0	0|1	0|1	0|0	0|0	0|0	0|1	0|0	0|0	0|0	0|1	0|0	0|0	1|0	0|0	0|00|0	0|0	0|0	0|0	0|1	0|0	0|0	0|0	0|0	1|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	1|0	0|0	0|1	0|0	0|1	0|0	0|0	0|0	0|00|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	1|0	0|0	0|0	0|10|0	0|0	0|0	0|0	0|0	0|0	0|0	0|1	0|0	0|0	0|0	1|0	0|0	0|1	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|1	0|0	0|1	0|00|0	0|0	0|0	0|0	0|0	0|0
```

**Comment by ANGSD** [comment]
For the subset of sites in your example none of these contain GP only GT. What the program tells you is that you do not have GP tags at those sites.
